version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fixops-postgres
    restart: always
    environment:
      POSTGRES_USER: fixops_admin
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fixops_db
    ports:
      - "5432:5432"
    volumes:
      - fixops_pgdata:/var/lib/postgresql/data

volumes:
  fixops_pgdata: